### PR TITLE
First pass at general coding guide

### PR DESCRIPTION
**Pull request by contolini**
After a handful of discussions, here's the first pass at a "definition of done" document. It is framed as a series of steps throughout the lifecycle of a project to encourage developers to reference it from the get-go instead of only when their project is complete.

## Additions

- Coding @ CFPB guide

## Testing

1. Preview it at https://github.com/cfpb/development/blob/coding-at-cfpb/guides/coding-at-cfpb.md

## Notes

- I'm open to any grammatical suggestions. It irks me a teeny bit that the verb tenses aren't consistent.

### CODE REVIEW

**Comment by stephanieosan** [comment]
Should there be something about analytics in here?

**Comment by contolini** [comment]
I'm inclined to say no because analytics shouldn't affect the code we write. Buuuuut it is important to consult with the analytics team and develop a game plan before releasing a project. Sometimes it's just a matter of throwing in a few event listeners, other times it's more complicated. Maybe we add a sentence in the release section about discussing analytics with one's team?

**Comment by willbarton** [comment]
> Maybe we add a sentence in the release section about discussing analytics with one's team?

I am in favor.

**Comment by contolini** [comment]
Mergin' this. It's a good start and we can improve it down the road.

**Pull request merged**
