### PR TITLE
npm usage

### PR DESCRIPTION
**Pull request by ascott1**
This PR introduces some rough guidelines for how we use npm.

### CODE REVIEW

**Comment by marteki** [comment]
Usability thought: it might be nice to link to this file from the `npm.md` file, in case new developers or other folks start looking there first.

**Comment by ascott1** [comment]
Great idea @marteki. I linked both npm documents, added a link from the README, and renamed the file to `npm-usage.md` (instead of (`using-npm.md`) to make it more discoverable by anyone just browsing the file names.

**Comment by ascott1** [comment]
Any objections to this being merged?

**Comment by jimmynotjim** [comment]
LGTM

**Comment by ascott1** [comment]
Merging

**Pull request merged**
